const $=s=>document.querySelector(s);const els={m3u:$('#m3uUrl'),proxy:$('#proxyUrl'),load:$('#loadBtn'),clear:$('#clearBtn'),search:$('#searchInput'),groups:$('#groupSelect'),chips:$('#categoryChips'),list:$('#channelList'),count:$('#channelCount'),adult:$('#adultToggle'),video:$('#video'),overlay:$('#playerOverlay'),nowTitle:$('#nowTitle'),nowGroup:$('#nowGroup'),nowLogo:$('#nowLogo'),fav:$('#favBtn'),prev:$('#prevBtn'),next:$('#nextBtn'),fs:$('#fullscreenBtn'),status:$('#statusBox'),settings:$('#settingsBtn'),setup:$('#setupPanel'),install:$('#installBtn')};
let channels=[],filtered=[],current=null,view='all';const player=new IPTVPlayer(els.video,els.status);let deferredInstall=null;
function init(){els.m3u.value=Store.get(Store.keys.m3u,'');els.proxy.value=Store.get(Store.keys.proxy,'https://solitary-sky-5274.yhasos.workers.dev/');els.adult.checked=Store.get(Store.keys.adult,false);bind();if(els.m3u.value)loadList(false)}
function bind(){els.load.onclick=()=>loadList(true);els.clear.onclick=clearAll;els.search.oninput=render;els.groups.onchange=render;els.adult.onchange=()=>{Store.set(Store.keys.adult,els.adult.checked);buildGroups();render()};els.fav.onclick=toggleFav;els.prev.onclick=()=>step(-1);els.next.onclick=()=>step(1);els.fs.onclick=()=>{const el=document.querySelector('.player-frame');if(el.requestFullscreen)el.requestFullscreen()};els.settings.onclick=()=>els.setup.classList.toggle('hidden');document.querySelectorAll('.quick-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.quick-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view;render()});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;els.install.classList.remove('hidden')});els.install.onclick=async()=>{if(deferredInstall){deferredInstall.prompt();deferredInstall=null;els.install.classList.add('hidden')}};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})}
async function loadList(showOk){const url=els.m3u.value.trim(),proxy=els.proxy.value.trim();if(!url)return alert('Pega primero la URL M3U');Store.set(Store.keys.m3u,url);Store.set(Store.keys.proxy,proxy);els.status.textContent='Descargando lista...';try{const finalUrl=proxy?proxy.replace(/\/?$/,'/')+'?url='+encodeURIComponent(url):url;const res=await fetch(finalUrl,{cache:'no-store'});if(!res.ok)throw new Error('HTTP '+res.status);const txt=await res.text();channels=parseM3U(txt);if(!channels.length)throw new Error('No se encontraron canales en la lista');buildGroups();render();els.setup.classList.add('hidden');els.status.textContent='Lista cargada: '+channels.length+' canales';if(showOk)alert('Lista cargada correctamente: '+channels.length+' canales');const last=Store.get(Store.keys.last,null);if(last){const ch=channels.find(c=>c.key===last);if(ch)selectChannel(ch,false)}}catch(e){alert('No se pudo cargar la lista: '+e.message);els.status.textContent='Error al cargar lista.'}}
function buildGroups(){els.groups.innerHTML='<option value="__all__">Todas las categorías</option>';groupsFrom(channels,els.adult.checked).forEach(g=>{const o=document.createElement('option');o.value=g.name;o.textContent=`${g.name} (${g.count})`;els.groups.appendChild(o)});const top=['ES','DAZN','Deportes','Cine','VOD','Adultos'];els.chips.innerHTML='';top.forEach(t=>{const b=document.createElement('button');b.textContent=t;b.onclick=()=>{els.search.value=t;els.groups.value='__all__';render()};els.chips.appendChild(b)})}
function favorites(){return Store.get(Store.keys.fav,[])}function recent(){return Store.get(Store.keys.recent,[])}function render(){const q=els.search.value.trim().toLowerCase();const g=els.groups.value;const favs=favorites();const rec=recent();filtered=channels.filter(c=>{if(c.adult&&!els.adult.checked)return false;if(g!=='__all__'&&c.group!==g)return false;if(view==='favorites'&&!favs.includes(c.key))return false;if(view==='recent'&&!rec.includes(c.key))return false;if(q&&!((c.name+' '+c.group).toLowerCase().includes(q)))return false;return true});if(view==='recent')filtered.sort((a,b)=>rec.indexOf(a.key)-rec.indexOf(b.key));els.count.textContent=`${filtered.length} / ${channels.length}`;els.list.innerHTML='';if(!filtered.length){els.list.innerHTML='<p class="hint">No hay canales.</p>';return}const frag=document.createDocumentFragment();filtered.forEach(ch=>{const row=document.createElement('div');row.className='channel'+(current&&current.key===ch.key?' active':'');row.onclick=()=>selectChannel(ch,true);if(ch.logo){const img=document.createElement('img');img.src=ch.logo;img.onerror=()=>img.replaceWith(noLogo());row.appendChild(img)}else row.appendChild(noLogo());const info=document.createElement('div');info.innerHTML=`<div class="channel-title">${esc(ch.name)}</div><div class="channel-group">${esc(ch.group)}</div>`;row.appendChild(info);if(favs.includes(ch.key)){const s=document.createElement('div');s.className='star';s.textContent='★';row.appendChild(s)}frag.appendChild(row)});els.list.appendChild(frag)}
function noLogo(){const d=document.createElement('div');d.className='no-logo';d.textContent='TV';return d}function esc(s){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function selectChannel(ch,autoplay){current=ch;Store.set(Store.keys.last,ch.key);const r=recent().filter(k=>k!==ch.key);r.unshift(ch.key);Store.set(Store.keys.recent,r.slice(0,30));els.nowTitle.textContent=ch.name;els.nowGroup.textContent=ch.group;els.overlay.classList.add('hidden');if(ch.logo){els.nowLogo.src=ch.logo;els.nowLogo.classList.remove('hidden')}else els.nowLogo.classList.add('hidden');updateFavBtn();render();if(autoplay)player.play(ch,els.proxy.value.trim())}
function updateFavBtn(){const favs=favorites();els.fav.textContent=current&&favs.includes(current.key)?'★ Favorito':'☆ Favorito'}function toggleFav(){if(!current)return;let favs=favorites();favs=favs.includes(current.key)?favs.filter(k=>k!==current.key):[...favs,current.key];Store.set(Store.keys.fav,favs);updateFavBtn();render()}function step(dir){if(!filtered.length)return;let i=current?filtered.findIndex(c=>c.key===current.key):-1;i=(i+dir+filtered.length)%filtered.length;selectChannel(filtered[i],true)}
function clearAll(){if(!confirm('¿Borrar URL, favoritos y ajustes?'))return;Object.values(Store.keys).forEach(k=>Store.del(k));location.reload()}
init();
